### ISSUE TITLE
Modificar rota de buscar databases

### ISSUE THREAD

**Issue by mrleonardobrito** [mrleonardobrito/plotnotion-backend#6]
## 📝Descrição do problema

Atualmente, a rota de retornar databases está retornando os databases, as propriedades e os dados de cada propriedade. Isso faz com que o tempo de resposta da API seja mais lento para essa rota, gerando delay em quem tá consumindo a API.

## 🎯Resolução

Para resolver esse problema a rota `/api/notion/databases` deve retornar apenas os databases e suas propriedades, sem os dados.

## 🚀Critérios 

- **Rota:** `/api/notion/databases`
- **Método:** GET
- Retorno:
```
[
  {
      "id": "dc07b7d8-8f71-44e0-8927-32cc96933c09",
      "name": "Database 1",
      "columns": [
          {
              "id": "%3B~Hq",
              "name": "Coluna 1",
              "type": "tipo_suportado",
          },
          {
              "id": "%3B~Hq",
              "name": "Coluna 2",
              "type": "tipo_suportado",
          },
   },
   {
       "id": "dc07b7d8-8f71-44e0-8927-32cc96933c09",
       "name": "Database 2",
       "columns": [
            {
                "id": "%3B~Hq",
                "name": "Coluna 1",
                "type": "tipo_suportado",
            },
            {
                "id": "%3B~Hq",
                "name": "Coluna 2",
                "type": "tipo_suportado",
            },
       },
]
```

## ✅ Todo list

- [ ] No arquivo `src/infra/notion/DatabaseNotionAPI.ts`, a função `getDatabases()` deve ser modificada:
   - [ ] A variável `columnsDTO`, que representa as propriedades da tabela, deve filtrar as propriedades suportadas antes de mapear elas para um DTO;
   - [ ] O que há da linha 72 até a 82 deve ser apagado;
   - [ ] A variável `columnsDTO` deve ser passada na propriedade columns do tipo DatabaseDTO
- [ ] Corrigir erros causados por essa mudança, se houver.
- [ ] Realizar testes unitários na rota utilizando jest.
- [ ] Rodar o projeto e testar a solução.
